Adding additional instructions for windows users when installing wrangler
cloudflare/workers-docs pull request #738
Opened 2020-04-14 15:17 UTC by silvererudite

I ran into some unnecessary trouble while running wrangler for the first time because it wasn't added to my computer's PATH. So I thought maybe it would be a good idea to add this information on the docs.

2020-04-20 15:37 UTC, signalnerve commented
i think this is a super useful change, i'm just not sure where the best place is for it. cc @cloudflare/workers-devexp – my question is if this should be in the docs or better suited for the wrangler repo. thanks for submitting a pr!!

2020-04-20 16:21 UTC, silvererudite commented
hi @signalnerve would be happy to modify any changes requested. Let me know if I need to move this PR to where  it's better suited.

2020-05-18 17:06 UTC, exvuma requested changes
Thanks for this! I think we can make this more concise without loosing information. Make sure to fix merge conflicts and run through a grammar checker for the extra spaces then happy to review again.

2020-05-18 17:06 UTC, victoriabernard92 commented on src/content/tooling/wrangler/install.md
> +After installing wrangler, you might need to add it to you Environment path if you don't have already.Otherwise you might face some unexpected problems when you run wrangller commands in you command
```suggestion
Wrangler needs to be in your path to run from the command line. Window's users see [How to Add to Windows PATH Environment Variable](https://helpdeskgeek.com/windows-10/add-windows-path-environment-variable/)
```

2020-10-01 20:59 UTC, rita3ko commented
Closing as we've migrated to a new repo, I opened an issue (https://github.com/cloudflare/cloudflare-docs/issues/32) since this is a great tip to document.

2020-10-01 20:59 UTC, closed without merging